# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: JMK Sandbox
email: 6500jmk4@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the sandbox site that accompanies the primary site for Dr. Jason M. Kelly (jasonmkelly.com). You will find digital humanities experiments, teaching materials, and a variety of materials related to my professional and personal interests. 

baseurl: "jmksandbox" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jason_m_kelly
github_username:  6500jmk4
linkedin_username: jason_m_kelly

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Aux links for the upper right navigation
aux_links:
  "Jason M. Kelly":
    - "//jasonmkelly.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.1"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

callouts:
  note:
      title: Note
      color: purple
      opacity: 0.3
  highlight:
      title: 
      color: yellow
      opacity: 0.3
  historiography:
      title: historiography
      color: blue
      opacity: 0.3
  method:
      title: method
      color: green
      opacity: 0.3


# For copy button on code
enable_copy_code_button: true


# External navigation links
nav_external_links:
  - title: Jason M. Kelly Website
    url: https://jasonmkelly.com/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

